const assert=require('node:assert/strict');
const {sample}=require('../static/city-timeline.js');
const start=Date.UTC(2030,0,1),duration=3600000;
const settings={disaster_started_at:new Date(start).toISOString(),start_at:new Date(start+duration).toISOString()};
assert.equal(sample({},start).progress,0);
assert.equal(sample(settings,start-1000).progress,0);
const interval=sample(settings,start).interval;
assert.equal(interval,15000);
assert.equal(sample(settings,start+interval-1).progress,0);
assert.equal(sample(settings,start+interval).progress,1/240);
for(const p of [.25,.5,.75,1])assert.equal(sample(settings,start+duration*p).progress,p);
assert(sample(settings,start+duration-1).progress<1);
assert.equal(sample(settings,start+duration).progress,1);
assert.equal(sample(settings,start+duration*5).remaining,0);
assert.equal(sample(JSON.parse(JSON.stringify(settings)),start+duration*.5).progress,.5,'serialized/reloaded timeline must match');
const short={disaster_started_at:new Date(start).toISOString(),start_at:new Date(start+5000).toISOString()};
assert.equal(sample(short,start).interval,1000);
assert.equal(sample(short,start+1000).progress,.2);
const long={...settings,start_at:new Date(start+86400000).toISOString()};
assert.equal(sample(long,start).interval,30000);
console.log('Timeline passed: interval boundaries, clean start, gradual progression, exact deadline, reload stability, and short/long timers.');
